apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-service
  template:
    metadata:
      labels:
        app: security-service
    spec:
      containers:
        - name: security-service
          image: faculty_management-security-service:latest
          ports:
            - containerPort: 8083
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 4
---
apiVersion: v1
kind: Service
metadata:
  name: security-service
spec:
  type: LoadBalancer
  selector:
    app: security-service
  ports:
    - port: 8083
      targetPort: 8083
