apiVersion: apps/v1
kind: Deployment
metadata:
  name: etudiant-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etudiant-service
  template:
    metadata:
      labels:
        app: etudiant-service
    spec:
      containers:
        - name: etudiant-service
          image: faculty_management-etudiant-service:latest
          ports:
            - containerPort: 8081
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 4
---
apiVersion: v1
kind: Service
metadata:
  name: etudiant-service
spec:
  type: LoadBalancer
  selector:
    app: etudiant-service
  ports:
    - port: 8081
      targetPort: 8081
